---
title: "Descriptive report: trial `r meta$title`"
author: "International Potato Center"
date: "September 18, 2015"
output: 
  html_document:
    theme: united
  pdf_document:
    toc: true
    highlight: zenburn
  word_document:
    highlight: "tango"
params: 
  meta: "no data"
  trait: "no data"
  treat: "no data"
  rep: "no data"
  data: "no data"
  maxp: "no data"
  author: "no data"

---


```{r, echo=FALSE}

fb = params$data
tr = params$trait
gt = params$treat
rp = params$rep
au = params$author
mp = params$maxp
meta = params$meta

#fb$CODE <- as.factor(fb$CODE)

```

The trait variable(s) is/are **`r paste(tr, collapse = ", ")`**; the genotype factor is **`r gt`**.
The replication factor is **`r rp`**.

Summary of traits:

```{r, echo=FALSE, comment = NA, results = 'asis'}
DF <- summary(fb[, tr]) 
#knitr::kable(DF, align = c("l","l","l","l"), padding = 8)
#print(xtable(DF,  align = c("l", "l","l","l","l") ), type = "html")
pander::pandoc.table(DF, justify = "llll")
```

```{r, echo=FALSE, results="asis"}
#tab <- xtable(summary(tbl)$coef, digits=c(0, 2, 2, 1, 2))
#print(tab, type="html")
```

```{r, echo=FALSE}
#hist(fb[[dp[1]]], main = dp, xlab = dp)
```



